project:
  type: default
  output-dir: _site

format:
  revealjs:
    theme: default
    slide-number: true
    embed-resources: true
    width: 1920
    height: 1080
    center: true
    css: style.css
    bibliography: references.bib
    link-external-newwindow: true
